### ISSUE TITLE
audio/video call

### ISSUE THREAD

**Issue by YXyjt** [matrix-org/matrix-android-sdk2-sample#13]
When can i expect audio/video call in this sample app

**Comment by bmarty** [comment]
We will not add more features to this sample app. This app is just showing how to setup the SDK to login, view room list, view timeline and send message.

For a full app implementation, you can refer to https://github.com/vector-im/element-android

**Comment by YXyjt** [comment]
This version is too complicated. Can you make a simple audio and video call version?

> 我们不会向此示例应用程序添加更多功能。这个应用程序只是展示了如何设置 SDK 来登录、查看房间列表、查看时间线和发送消息。
> 
> 完整的应用实现，可以参考https://github.com/vector-im/element-android

This version is too complicated. Can you make a simple audio and video call version?
