### ISSUE TITLE
How to get media URL from MXC url in android

### ISSUE THREAD

**Issue by DharmendraRughani9911** [matrix-org/matrix-android-sdk2-sample#18]
I wanted to get the base URL of media from MXC URL.

In iOS there is a class called MXMediaManager , is there any similar class in android to get the original media URL from MXC URL or from session?

if you guys can provide the example then it would be great.

**Comment by DharmendraRughani9911** [comment]
Marking it as resolved , as can able to render image using below Method of Session class

**contentUrlResolver**

**Comment by DerTeufel** [comment]
i can get the url using contentUrlResolver like this:
val resolvedUrl = SessionHolder.currentSession?.contentUrlResolver()?.resolveForDownload(url)?.toString()

but i can't access the resolved url. for example i get this: https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/DwsbwRunujacUXMXimionree

more details from the log:
```
09-25 00:03:54.678 14259 14259 D TimelineEventMessageWrapper: msgtype: m.image
09-25 00:03:54.678 14259 14259 D TimelineEventMessageWrapper: body: JPEG_20240925_130033_6310192692037663948.jpg
09-25 00:03:54.678 14259 14259 D TimelineEventMessageWrapper: info: ImageInfo(mimeType=image/jpeg, width=948, height=474, size=43693, thumbnailInfo=null, thumbnailUrl=null, thumbnailFile=null)
09-25 00:03:54.679 14259 14259 D TimelineEventMessageWrapper: url: mxc://matrix.org/DwsbwRunujacUXMXimionree
```
is there something wrong on my sender side, to allow accessing the sent image?
Any ideas @DharmendraRughani9911
