### ISSUE TITLE
Group Chat Functionality Flow

### ISSUE THREAD

**Issue by ShriChanaveer** [matrix-org/matrix-android-sdk2-sample#3]
Hi Team

I was going through the sample available here and I couldn't find flow about group chat creation and working of it . so it will be very helpful for me if you guide or suggest solution for it from your SDK.

**Comment by bmarty** [comment]
You have to call [session.createRoom()](https://github.com/vector-im/element-android/blob/develop/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/session/room/RoomService.kt#L36). You can also check how it is done in Element Android. The sample is not supposed to cover all what we can do with the SDK, but yes, maybe add a quick way to create a room can be possible.

**Comment by bmarty** [comment]
You can refer to the Matrix SDK API documentation: https://matrix-org.github.io/matrix-android-sdk2/
