### ISSUE TITLE
Share files/images functionality

### ISSUE THREAD

**Issue by mzfr** [matrix-org/matrix-android-sdk2-sample#4]
I was wondering if there is any way to use this SDK and share the data? 
By sharing the data I mean to say someone wants to put a file/image in a room.

It would be nice if someone can provide me some code examples related to this. If sharing the code then please let me know the activity being called with all the extras etc

If there is any function/module then please let me know about that.

**Comment by bmarty** [comment]
You can try to see how we are doing that in [Element Android](https://github.com/vector-im/element-android)

**Comment by mzfr** [comment]
@bmarty I did look at the source code of the element app and things are a bit unclear to me in the code. That is why I asked for a small example about calling the activity etc

I also tried to ask questions on the `#element-android:matrix.org` channel but unfortunately, no one responded.
It maybe is too much to ask but if possible can you please provide some code examples like if there is an activity, what all extras or required parameters are to be sent to it etc.

**Comment by bmarty** [comment]
We will not add more features to this sample app. This app is just showing how to setup the SDK to login, view room list, view timeline and send message.

For a full app implementation, you can refer to https://github.com/vector-im/element-android

Also you can refer to the Matrix SDK API documentation: https://matrix-org.github.io/matrix-android-sdk2/
