### ISSUE TITLE
Why the sdk is so large

### ISSUE THREAD

**Issue by gutongjiang** [matrix-org/matrix-android-sdk2-sample#6]
Hi, I'm trying to use the android sdk, but I found that the size of the sdk is too large, I have tried to remove the audio and video parts, but it is still too large

**Comment by bmarty** [comment]
The latest AAR (https://jitpack.io/com/github/matrix-org/matrix-android-sdk2/v1.1.1/matrix-android-sdk2-v1.1.1.aar) is 7.1 Mbytes, which seems OK to me.
