### ISSUE TITLE
Unable to connect to homeserver

### ISSUE THREAD

**Issue by nich01as** [matrix-org/matrix-android-sdk2-sample#9]
I cloned the repository in Android Studios and was able to install the SDK on my phone, but when I entered my homeserver url, it recognized it as invalid.

I tried connecting to the same homeserver on the Element app off Playstore and it worked.

**Comment by bmarty** [comment]
make sure you prefix the url with `https://`. The sample is not as powerful as Element Android

**Comment by himanshuRajNeosoft** [comment]
isn't working at all, by adding same.
